language: java
jdk:
    #- oraclejdk8
    - openjdk8

cache:
    directories:
        - ${HOME}/.m2

before_install:
    - ulimit -a && free -m
    - chmod +x -R .mvn/*
    - chmod +x mvnw
    - wget -O ~/codacy-coverage-reporter-assembly-latest.jar "https://github.com/codacy/codacy-coverage-reporter/releases/download/6.0.6/codacy-coverage-reporter-6.0.6-assembly.jar"

install:


addons:
    sonarcloud:
        organization: "nikoniko-team"
        token:
            secure: "${SONAR_TOKEN}"
script:
    - ./mvnw install -B -V
    - ./mvnw clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=nikoniko-team_nikoniko-backend
    - ulimit -a && free -m

before_cache:


after_success:
    - bash <(curl -s https://codecov.io/bash)
    - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/site/jacoco/jacoco.xml

after_failure:
    - echo "FAILURE"
    - ulimit -a
    - free -m

before_deploy:


deploy:
    provider: heroku
    api_key:
        secure: "${HEROKU_API_KEY}"
    app:
        master: hom-nikoniko-backend
        production: prod-nikoniko-backend

after_deploy:

after_script:
